# Generated by Django 6.0.6 on 2026-09-05 02:49

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alumno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dni', models.CharField(max_length=20, unique=True, validators=[django.core.validators.RegexValidator(message='Ingrese un número de documento válido.', regex='^[0-9A-Za-z.\\-]{6,20}$')], verbose_name='DNI / Documento')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre')),
                ('apellido', models.CharField(max_length=100, verbose_name='Apellido')),
                ('fecha_nacimiento', models.DateField(verbose_name='Fecha de Nacimiento')),
                ('email', models.EmailField(max_length=254, verbose_name='Correo Electrónico')),
                ('telefono', models.CharField(max_length=50, verbose_name='Teléfono')),
                ('direccion', models.CharField(max_length=200, verbose_name='Dirección')),
                ('codigo_postal', models.CharField(max_length=20, verbose_name='Código Postal')),
                ('genero', models.CharField(choices=[('M', 'Masculino'), ('F', 'Femenino'), ('I', 'Indistinto')], max_length=1, verbose_name='Género')),
                ('nacionalidad', models.CharField(choices=[('Argentina', 'Argentina'), ('Boliviana', 'Boliviana'), ('Brasileña', 'Brasileña'), ('Chilena', 'Chilena'), ('Colombiana', 'Colombiana'), ('Ecuatoriana', 'Ecuatoriana'), ('Española', 'Española'), ('Italiana', 'Italiana'), ('Paraguaya', 'Paraguaya'), ('Peruana', 'Peruana'), ('Uruguaya', 'Uruguaya'), ('Venezolana', 'Venezolana'), ('Otra', 'Otra')], default='Argentina', max_length=50, verbose_name='Nacionalidad')),
                ('pais_residencia', models.CharField(choices=[('Argentina', 'Argentina'), ('Bolivia', 'Bolivia'), ('Brasil', 'Brasil'), ('Chile', 'Chile'), ('Colombia', 'Colombia'), ('Ecuador', 'Ecuador'), ('España', 'España'), ('Italia', 'Italia'), ('Paraguay', 'Paraguay'), ('Perú', 'Perú'), ('Uruguay', 'Uruguay'), ('Venezuela', 'Venezuela'), ('Otro', 'Otro')], default='Argentina', max_length=50, verbose_name='País de Residencia')),
                ('fecha_registro', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Registro')),
            ],
            options={
                'verbose_name': 'Alumno',
                'verbose_name_plural': 'Alumnos',
                'db_table': 'carga_alumnos_alumno',
                'ordering': ['-fecha_registro', 'apellido', 'nombre'],
            },
        ),
    ]
