# Generated by Django 6.0.6 on 2026-09-05 04:28

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carga_alumnos', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alumno',
            name='codigo_postal',
        ),
        migrations.AddField(
            model_name='alumno',
            name='cuil',
            field=models.CharField(blank=True, db_index=True, default='', max_length=20, validators=[django.core.validators.RegexValidator(message='Ingrese un CUIL válido (11 dígitos numéricos o formato XX-XXXXXXXX-X).', regex='^\\d{2}-?\\d{8}-?\\d{1}$')], verbose_name='CUIL'),
        ),
        migrations.AlterField(
            model_name='alumno',
            name='dni',
            field=models.CharField(db_index=True, max_length=20, unique=True, validators=[django.core.validators.RegexValidator(message='Ingrese un número de DNI válido (entre 6 y 10 dígitos numéricos).', regex='^\\d{6,10}$')], verbose_name='DNI / Documento'),
        ),
        migrations.AlterField(
            model_name='alumno',
            name='genero',
            field=models.CharField(choices=[('M', 'Masculino'), ('F', 'Femenino'), ('I', 'Indistinto'), ('N', 'Prefiere no decir')], default='N', max_length=1, verbose_name='Género'),
        ),
    ]
