# Generated by Django 6.0.6 on 2026-09-05 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carga_alumnos', '0002_remove_alumno_codigo_postal_alumno_cuil_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alumno',
            name='pais_residencia',
        ),
        migrations.AddField(
            model_name='alumno',
            name='localidad',
            field=models.CharField(choices=[('General Rodríguez', 'General Rodríguez'), ('Moreno', 'Moreno'), ('Luján', 'Luján'), ('Pilar', 'Pilar'), ('Mercedes', 'Mercedes'), ('San Miguel', 'San Miguel'), ('Marcos Paz', 'Marcos Paz'), ('Merlo', 'Merlo'), ('Morón', 'Morón'), ('Ituzaingó', 'Ituzaingó'), ('Hurlingham', 'Hurlingham'), ('José C. Paz', 'José C. Paz'), ('Malvinas Argentinas', 'Malvinas Argentinas'), ('Jáuregui', 'Jáuregui'), ('Navarro', 'Navarro'), ('CABA', 'CABA (Ciudad Autónoma de Buenos Aires)'), ('Otra Localidad', 'Otra Localidad')], default='General Rodríguez', max_length=100, verbose_name='Localidad'),
        ),
    ]
