# Generated by Django 6.0.6 on 2026-09-05 05:24

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carga_alumnos', '0003_remove_alumno_pais_residencia_alumno_localidad'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alumno',
            name='cuil',
            field=models.CharField(blank=True, db_index=True, default='', max_length=20, validators=[django.core.validators.RegexValidator(message='Ingrese un número de CUIL, CDI o identificación válido.', regex='^[a-zA-Z0-9\\.\\-\\s]{4,20}$')], verbose_name='CUIL / Identificación'),
        ),
        migrations.AlterField(
            model_name='alumno',
            name='dni',
            field=models.CharField(db_index=True, max_length=20, unique=True, validators=[django.core.validators.RegexValidator(message='Ingrese un número de documento, pasaporte o DNI válido (entre 4 y 20 caracteres).', regex='^[a-zA-Z0-9\\.\\-\\s]{4,20}$')], verbose_name='DNI / Documento'),
        ),
        migrations.AlterField(
            model_name='alumno',
            name='nacionalidad',
            field=models.CharField(default='Argentina', max_length=100, verbose_name='Nacionalidad'),
        ),
    ]
