# Generated by Django 6.0.6 on 2026-09-05 05:58

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carga_alumnos', '0004_alter_alumno_cuil_alter_alumno_dni_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alumno',
            name='cuil',
            field=models.CharField(blank=True, db_index=True, default='', max_length=20, validators=[django.core.validators.RegexValidator(message='Ingrese un número de CUIL válido de 11 dígitos numéricos.', regex='^\\d{2}-\\d{8}-\\d{1}$|^\\d{11}$')], verbose_name='CUIL'),
        ),
        migrations.AlterField(
            model_name='alumno',
            name='dni',
            field=models.CharField(db_index=True, max_length=20, unique=True, validators=[django.core.validators.RegexValidator(message='Ingrese un número de DNI válido de 7 u 8 dígitos.', regex='^\\d{7,8}$')], verbose_name='DNI'),
        ),
    ]
