# Generated by Django 6.0.6 on 2026-08-03 01:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('id_persona', models.AutoField(primary_key=True, serialize=False)),
                ('dni', models.CharField(db_index=True, max_length=20, unique=True, verbose_name='DNI')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre')),
                ('apellido', models.CharField(max_length=100, verbose_name='Apellido')),
                ('domicilio', models.CharField(blank=True, max_length=200, null=True, verbose_name='Domicilio')),
                ('telefono', models.CharField(blank=True, max_length=50, null=True, verbose_name='Teléfono')),
                ('mail', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Correo Electrónico')),
            ],
            options={
                'verbose_name': 'Persona',
                'verbose_name_plural': 'Personas',
                'ordering': ['apellido', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='Carrera',
            fields=[
                ('codigo_carrera', models.CharField(max_length=50, primary_key=True, serialize=False, verbose_name='Código Carrera')),
                ('nombre_carrera', models.CharField(max_length=200, verbose_name='Nombre de la Carrera')),
                ('resolucion_vigente', models.CharField(blank=True, max_length=100, null=True, verbose_name='Resolución Vigente')),
                ('resolucion_anterior', models.CharField(blank=True, max_length=100, null=True, verbose_name='Resolución Anterior')),
            ],
            options={
                'verbose_name': 'Carrera',
                'verbose_name_plural': 'Carreras',
            },
        ),
        migrations.CreateModel(
            name='Comision',
            fields=[
                ('codigo_comision', models.CharField(max_length=50, primary_key=True, serialize=False, verbose_name='Código Comisión')),
                ('anio_lectivo', models.IntegerField(default=2026, verbose_name='Año Lectivo')),
                ('cuatrimestre', models.CharField(default='Anual', max_length=20, verbose_name='Cuatrimestre')),
                ('turno', models.CharField(default='Vespertino', max_length=20, verbose_name='Turno')),
                ('division', models.CharField(default='A', max_length=10, verbose_name='División')),
            ],
            options={
                'verbose_name': 'Comisión',
                'verbose_name_plural': 'Comisiones',
            },
        ),
        migrations.CreateModel(
            name='Materia',
            fields=[
                ('codigo_materia', models.CharField(max_length=50, primary_key=True, serialize=False, verbose_name='Código Materia')),
                ('nombre_materia', models.CharField(max_length=200, verbose_name='Nombre de la Materia')),
            ],
            options={
                'verbose_name': 'Materia',
                'verbose_name_plural': 'Materias',
            },
        ),
        migrations.CreateModel(
            name='Alumno',
            fields=[
                ('persona', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='alumno_profile', serialize=False, to='gestion.persona')),
                ('legajo', models.CharField(blank=True, max_length=50, null=True, verbose_name='N° Legajo')),
            ],
            options={
                'verbose_name': 'Alumno',
                'verbose_name_plural': 'Alumnos',
            },
        ),
        migrations.CreateModel(
            name='Docente',
            fields=[
                ('persona', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='docente_profile', serialize=False, to='gestion.persona')),
                ('titulo_mn', models.CharField(blank=True, max_length=150, null=True, verbose_name='Título / Matrícula Nacional')),
            ],
            options={
                'verbose_name': 'Docente',
                'verbose_name_plural': 'Docentes',
            },
        ),
        migrations.CreateModel(
            name='Cursada',
            fields=[
                ('id_cursada', models.AutoField(primary_key=True, serialize=False)),
                ('porcentaje_asistencia', models.DecimalField(decimal_places=2, default=0.0, max_digits=5, verbose_name='% Asistencia')),
                ('situacion_final', models.CharField(choices=[('Promocionado', 'Promocionado'), ('Final', 'A Final'), ('Regular', 'Regular'), ('Libre', 'Libre / Recursa'), ('En Cursada', 'En Cursada')], default='Regular', max_length=50, verbose_name='Situación Final')),
                ('comision', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cursadas', to='gestion.comision')),
                ('alumno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cursadas', to='gestion.alumno')),
            ],
            options={
                'verbose_name': 'Cursada',
                'verbose_name_plural': 'Cursadas',
                'unique_together': {('comision', 'alumno')},
            },
        ),
        migrations.CreateModel(
            name='Evaluacion',
            fields=[
                ('codigo_evaluacion', models.AutoField(primary_key=True, serialize=False)),
                ('instancia', models.CharField(max_length=50, verbose_name='Instancia (Ej: Parcial 1, Recup, Nota Final)')),
                ('nota', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True, verbose_name='Nota')),
                ('fecha', models.DateField(blank=True, null=True, verbose_name='Fecha')),
                ('cursada', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluaciones', to='gestion.cursada')),
            ],
            options={
                'verbose_name': 'Evaluación',
                'verbose_name_plural': 'Evaluaciones',
            },
        ),
        migrations.CreateModel(
            name='PlanEstudio',
            fields=[
                ('id_plan', models.AutoField(primary_key=True, serialize=False)),
                ('anio_carrera', models.IntegerField(default=1, verbose_name='Año de Carrera')),
                ('modalidad', models.CharField(default='Cuatrimestral', max_length=50, verbose_name='Modalidad')),
                ('carga_horaria_anual', models.IntegerField(blank=True, null=True, verbose_name='Carga Horaria Anual')),
                ('carga_horaria_semanal', models.IntegerField(blank=True, null=True, verbose_name='Carga Horaria Semanal')),
                ('correlatividades', models.CharField(blank=True, default='', max_length=200, verbose_name='Correlatividades')),
                ('carrera', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='planes_estudio', to='gestion.carrera')),
                ('materia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='planes_estudio', to='gestion.materia')),
            ],
            options={
                'verbose_name': 'Plan de Estudio',
                'verbose_name_plural': 'Planes de Estudio',
                'ordering': ['carrera', 'anio_carrera', 'materia'],
            },
        ),
        migrations.AddField(
            model_name='comision',
            name='plan_estudio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comisiones', to='gestion.planestudio'),
        ),
        migrations.CreateModel(
            name='ComisionDocente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rol', models.CharField(default='Titular', max_length=50, verbose_name='Rol Docente')),
                ('comision', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='docentes_asignados', to='gestion.comision')),
                ('docente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comisiones_asignadas', to='gestion.docente')),
            ],
            options={
                'verbose_name': 'Docente en Comisión',
                'verbose_name_plural': 'Docentes en Comisiones',
                'unique_together': {('comision', 'docente')},
            },
        ),
    ]
