# Generated by Django 6.0.6 on 2026-08-17 04:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='carrera',
            options={'ordering': ['nombre_carrera'], 'verbose_name': 'Carrera', 'verbose_name_plural': 'Carreras'},
        ),
        migrations.AlterModelOptions(
            name='comision',
            options={'ordering': ['anio_lectivo', 'codigo_comision'], 'verbose_name': 'Comisión', 'verbose_name_plural': 'Comisiones'},
        ),
        migrations.AlterModelOptions(
            name='materia',
            options={'ordering': ['nombre_materia'], 'verbose_name': 'Materia', 'verbose_name_plural': 'Materias'},
        ),
        migrations.AddField(
            model_name='persona',
            name='cuil',
            field=models.CharField(blank=True, db_index=True, max_length=20, null=True, verbose_name='CUIL'),
        ),
        migrations.AddField(
            model_name='persona',
            name='fecha_nacimiento',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de Nacimiento'),
        ),
        migrations.AddField(
            model_name='persona',
            name='identidad',
            field=models.CharField(choices=[('M', 'Masculino'), ('F', 'Femenino'), ('O', 'Otro'), ('N', 'Prefiere no decir')], db_index=True, default='N', max_length=1, verbose_name='Identidad de Género'),
        ),
        migrations.AddField(
            model_name='persona',
            name='localidad',
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True, verbose_name='Localidad'),
        ),
        migrations.AddField(
            model_name='persona',
            name='nacionalidad',
            field=models.CharField(blank=True, default='Argentina', max_length=100, null=True, verbose_name='Nacionalidad'),
        ),
        migrations.AlterField(
            model_name='alumno',
            name='legajo',
            field=models.CharField(blank=True, db_index=True, max_length=50, null=True, verbose_name='N° Legajo'),
        ),
        migrations.AlterField(
            model_name='comision',
            name='plan_estudio',
            field=models.ForeignKey(db_column='id_plan', on_delete=django.db.models.deletion.CASCADE, related_name='comisiones', to='gestion.planestudio'),
        ),
        migrations.AlterField(
            model_name='comisiondocente',
            name='comision',
            field=models.ForeignKey(db_column='codigo_comision', on_delete=django.db.models.deletion.CASCADE, related_name='docentes_asignados', to='gestion.comision'),
        ),
        migrations.AlterField(
            model_name='comisiondocente',
            name='docente',
            field=models.ForeignKey(db_column='id_persona_docente', on_delete=django.db.models.deletion.CASCADE, related_name='comisiones_asignadas', to='gestion.docente'),
        ),
        migrations.AlterField(
            model_name='cursada',
            name='alumno',
            field=models.ForeignKey(db_column='id_persona_alumno', on_delete=django.db.models.deletion.CASCADE, related_name='cursadas', to='gestion.alumno'),
        ),
        migrations.AlterField(
            model_name='cursada',
            name='comision',
            field=models.ForeignKey(db_column='codigo_comision', on_delete=django.db.models.deletion.CASCADE, related_name='cursadas', to='gestion.comision'),
        ),
        migrations.AlterField(
            model_name='cursada',
            name='id_cursada',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='ID Cursada'),
        ),
        migrations.AlterField(
            model_name='cursada',
            name='porcentaje_asistencia',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='% Asistencia'),
        ),
        migrations.AlterField(
            model_name='evaluacion',
            name='codigo_evaluacion',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='Código Evaluación'),
        ),
        migrations.AlterField(
            model_name='evaluacion',
            name='cursada',
            field=models.ForeignKey(db_column='id_cursada', on_delete=django.db.models.deletion.CASCADE, related_name='evaluaciones', to='gestion.cursada'),
        ),
        migrations.AlterField(
            model_name='persona',
            name='id_persona',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='ID Persona'),
        ),
        migrations.AlterField(
            model_name='persona',
            name='telefono',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Teléfono / Celular'),
        ),
        migrations.AlterField(
            model_name='planestudio',
            name='carga_horaria_semanal',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True, verbose_name='Carga Horaria Semanal'),
        ),
        migrations.AlterField(
            model_name='planestudio',
            name='carrera',
            field=models.ForeignKey(db_column='codigo_carrera', on_delete=django.db.models.deletion.CASCADE, related_name='planes_estudio', to='gestion.carrera'),
        ),
        migrations.AlterField(
            model_name='planestudio',
            name='id_plan',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='ID Plan'),
        ),
        migrations.AlterField(
            model_name='planestudio',
            name='materia',
            field=models.ForeignKey(db_column='codigo_materia', on_delete=django.db.models.deletion.CASCADE, related_name='planes_estudio', to='gestion.materia'),
        ),
        migrations.AlterField(
            model_name='planestudio',
            name='modalidad',
            field=models.CharField(default='Anual', max_length=50, verbose_name='Modalidad'),
        ),
    ]
