# Generated by Django 6.0.6 on 2026-08-30 00:20

from django.db import migrations, models


def migrar_genero_o_a_i(apps, schema_editor):
    Persona = apps.get_model('gestion', 'Persona')
    Persona.objects.filter(identidad='O').update(identidad='I')

def revertir_genero_i_a_o(apps, schema_editor):
    Persona = apps.get_model('gestion', 'Persona')
    Persona.objects.filter(identidad='I').update(identidad='O')


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0002_alter_carrera_options_alter_comision_options_and_more'),
    ]

    operations = [
        migrations.RunPython(migrar_genero_o_a_i, revertir_genero_i_a_o),
        migrations.AlterField(
            model_name='persona',
            name='identidad',
            field=models.CharField(choices=[('M', 'Masculino'), ('F', 'Femenino'), ('I', 'Indistinto'), ('N', 'Prefiere no decir')], db_index=True, default='N', max_length=1, verbose_name='Identidad de Género'),
        ),
        migrations.AlterField(
            model_name='persona',
            name='nacionalidad',
            field=models.CharField(blank=True, db_index=True, default='Argentina', max_length=100, null=True, verbose_name='Nacionalidad'),
        ),
    ]
